services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: acj_api
    environment:
      - FLASK_ENV=development
    ports:
      - "8000:8000"
    restart: unless-stopped
